# Google Cloud Build configuration for Job Application Agent
# Automates building, testing, and deploying to Google Cloud Platform

steps:
  # Step 1: Build image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/job-agent:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/job-agent:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
  
  # Step 2: Run tests in container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test'
    args:
      - 'run'
      - '--rm'
      - 'gcr.io/$PROJECT_ID/job-agent:$SHORT_SHA'
      - 'bash'
      - '-c'
      - |
        pip install pytest pytest-cov
        pytest tests/ -v --cov=src --cov-report=term-missing
    waitFor: ['build']
  
  # Step 3: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/job-agent:$SHORT_SHA'
    waitFor: ['test']
  
  # Step 4: Update Container Registry image tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/job-agent:latest'
    waitFor: ['test']
  
  # Step 5: Deploy to Cloud Run (Staging)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-staging'
    args:
      - 'run'
      - '--service-account=$_SERVICE_ACCOUNT'
      - '--namespace=$_NAMESPACE'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_ZONE'
      - '--filename=kubernetes/'
      - '--image=gcr.io/$PROJECT_ID/job-agent:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER'
    waitFor: ['push']
  
  # Step 6: Run smoke tests
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'smoke-test'
    args:
      - 'run'
      - 'smoke-test'
      - '--image=gcr.io/cloud-builders/kubectl'
      - '--'
      - 'bash'
      - '-c'
      - |
        sleep 10
        kubectl get pods -n staging
        kubectl rollout status deployment/job-agent -n staging
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER'
    waitFor: ['deploy-staging']
  
  # Step 7: Deploy to Cloud Run (Production) - Manual approval
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-prod'
    args:
      - 'run'
      - '--service-account=$_SERVICE_ACCOUNT'
      - '--namespace=$_NAMESPACE_PROD'
      - '--cluster=$_GKE_CLUSTER_PROD'
      - '--location=$_GKE_ZONE_PROD'
      - '--filename=kubernetes/'
      - '--image=gcr.io/$PROJECT_ID/job-agent:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_ZONE_PROD'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER_PROD'
    waitFor: ['smoke-test']
    onFailure: ['ALLOW']
  
  # Step 8: Send Slack notification
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'notify'
    args:
      - 'run'
      - '--'
      - 'bash'
      - '-c'
      - |
        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "Build ${BUILD_ID} completed",
            "attachments": [
              {
                "color": "good",
                "fields": [
                  {"title": "Status", "value": "Success", "short": true},
                  {"title": "Image", "value": "gcr.io/${PROJECT_ID}/job-agent:${SHORT_SHA}", "short": true},
                  {"title": "Branch", "value": "${BRANCH_NAME}", "short": true}
                ]
              }
            ]
          }' \
          $$SLACK_WEBHOOK_URL
    waitFor: ['deploy-prod']
    onFailure: ['CONTINUE']

# Substitution variables
substitutions:
  _GKE_CLUSTER: 'job-agent-cluster'
  _GKE_ZONE: 'us-central1-a'
  _GKE_CLUSTER_PROD: 'job-agent-prod-cluster'
  _GKE_ZONE_PROD: 'us-central1-a'
  _NAMESPACE: 'staging'
  _NAMESPACE_PROD: 'production'
  _SERVICE_ACCOUNT: 'cloud-builder@${PROJECT_ID}.iam.gserviceaccount.com'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Images
images:
  - 'gcr.io/$PROJECT_ID/job-agent:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/job-agent:latest'

# Build timeout
timeout: '3600s'

# On failure
onFailure:
  - 'NOTIFY'

# Artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild'
    paths:
      - 'test-results.xml'
      - 'coverage.xml'

# Build id
# This is auto-generated - do not edit

tags:
  - 'gcp-cloud'
  - 'job-agent'
  - '${BRANCH_NAME}'
  - '${COMMIT_SHA}'

# Secrets
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/slack-webhook/versions/latest
      env: 'SLACK_WEBHOOK_URL'
    - versionName: projects/$PROJECT_ID/secrets/docker-registry-token/versions/latest
      env: 'DOCKER_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: 'GITHUB_TOKEN'
